const Menu=[
  {
    id:1,
    image:"../images/maggi.jpg",
    name:"Maggi",
    category:"Breakfast",
    price:"20₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:2,
    image:"../images/alo pakora.jpg",
    name:"Allu Pakoda",
    category:"Evening",
    price:"40₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:3,
    image:"../images/corn.jpg",
    name:"corn",
    category:"Breakfast",
    price:"10₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:4,
    image:"../images/chola.jpg",
    name:"chola",
    category:"Lunch",
    price:"50₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:5,
    image:"../images/pizza.jpg",
    name:"pizza",
    category:"Evening",
    price:"80₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:6,
    image:"../images/veg-thali.jpg",
    name:"Veg Thali",
    category:"Dinner",
    price:"180₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:7,
    image:"../images/sweets.jpg",
    name:"Sweets",
    category:"Dinner",
    price:"60₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:8,
    image:"../images/rajma-rice.jpg",
    name:"Rajma Rice",
    category:"Lunch",
    price:"60₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:9,
    image:"../images/samosa.jpg",
    name:"Samosa",
    category:"Evening",
    price:"10₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:10,
    image:"../images/ice-cream.jpg",
    name:"Ice-Cream",
    category:"Timepass",
    price:"35₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:11,
    image:"../images/cake.jpeg",
    name:"Cake",
    category:"Timepass",
    price:"10₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },
  {
    id:12,
    image:"../images/fuchka.jpg",
    name:"Fuchka",
    category:"Timepass",
    price:"10₹",
    description:"Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
  },

]
export default Menu;